### ISSUE TITLE
Bazel rules for calling Pandoc

### ISSUE THREAD

**Issue by EdSchouten** [jin/awesome-bazel#12]
Hi Jingwen,

I see your awesome (!) awesome-bazel page mentions the LaTeX rules that I maintain. Similar to those, I recently published rules for calling [Pandoc](https://pandoc.org/) to convert between document formats. It makes use of the official Pandoc release binaries instead of relying on the one provided by your OS/distro. At Prodrive, we use these together with the LaTeX rules to combine documentation from various sources into larger works (e.g., user manuals).

https://github.com/ProdriveTechnologies/bazel-pandoc

I don't think that I, as the author, should have a say in whether this classifies as being awesome or not. Still, I thought I'd get in touch to point you to it. Thanks!

**Comment by jin** [comment]
Please open a PR to add your awesome rules :-)

**Comment by jin** [comment]
Added in https://github.com/jin/awesome-bazel/commit/093452fc181aed40e551c889becf838b8d6f7dec
