### ISSUE TITLE
New resource sections needed

### ISSUE THREAD

**Issue by jxramos** [jin/awesome-bazel#49]
As far as I can tell there's no published reference books on the market, but one is coming soon landing December 24th this year (what a release date). Should be worth referencing it in this fantastic list you have curated and break open a new section to contain future references we expect to be coming.

https://www.amazon.com/Beginning-Bazel-Building-Testing-Java/dp/1484251938

**Comment by jxramos** [comment]
Podcasts too should be worthwhile.

> Google Cloud Podcast
> #153 | Oct 31, 2018
> Bazel with Tony Aiuto
> https://www.gcppodcast.com/categories/bazel/


> Adventures in Angular
> AiA 247: Bazel with Alex Eagle
> https://player.fm/series/all-angular-podcasts-by-devchattv/aia-247-bazel-with-alex-eagle

**Comment by jin** [comment]
Addressed in https://github.com/jin/awesome-bazel/pull/50, thanks @jxramos!
